---
apiVersion: messaging.knative.dev/v1beta1
kind: Subscription
metadata:
  name: sample-subscription
spec:
  channel:
    apiVersion: messaging.knative.dev/v1beta1
    kind: Channel
    name: sample-channel
  #delivery: 
  #  deadLetterSink:
  #    ref:
  #      apiVersion: serving.knative.dev/v1
  #      kind: Service
  #      name: error-handler
  subscriber: 
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
