---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  annotations:
    eventing.knative.dev/injection: enabled
  name: sample-trigger
spec:
  broker: default
  subscriber: 
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display
