apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - event-bus-kafka-kafka-bootstrap.knative-demo-eventing:9092
  topics:
  - events
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: event-display