apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: prime-generator-cpu
spec:
  template:
    metadata:
      annotations:
        # Standard Kubernetes CPU-based autoscaling.
        autoscaling.knative.dev/class: hpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: cpu
        autoscaling.knative.dev/target: "40"
        # Minimum number of pods
        #autoscaling.knative.dev/minScale: "1"
        # Maximum number of pods
        #autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
      - image: quay.io/rhdevelopers/prime-generator:v27-quarkus
        livenessProbe:
          httpGet:
            path: /healthz
        readinessProbe:
          httpGet:
            path: /healthz